test_subject <- read.table("C:/DATA/UCI HAR Dataset/test/subject_test.txt",stringsAsFactors = FALSE)
library(dplyr)
library(readr)
library(tidyverse)
test_subject<-tbl_df(test_subject)
test_subject<-test_subject %>% rename(subject=V1)
train_subject <- read.table("C:/DATA/UCI HAR Dataset/train/subject_train.txt",stringsAsFactors = FALSE)
train_subject<-tbl_df(train_subject)
train_subject<-train_subject %>% rename(subject=V1)
y_train <- read.table("C:/DATA/UCI HAR Dataset/train/y_train.txt",stringsAsFactors = FALSE)
X_train <- read.table("C:/DATA/UCI HAR Dataset/train/X_train.txt")
y_test <- read.table("C:/DATA/UCI HAR Dataset/test/y_test.txt",stringsAsFactors = FALSE)
X_test <- read.table("C:/DATA/UCI HAR Dataset/test/X_test.txt")
y_train<-y_train %>% rename(lable=V1)
y_test<- y_test %>% rename (lable=V1)
body_acc_x_test <- read.table("C:/DATA/UCI HAR Dataset/test/Inertial Signals/body_acc_x_test.txt",stringsAsFactors = FALSE)
features <- read.table("C:/DATA/UCI HAR Dataset/features.txt",stringsAsFactors = FALSE)
features<- features %>% rename (feature_id=V1, feature=V2)
X_test<- X_test %>% column_to_rownames(var = features$feature)
